# -*- coding: utf-8 -*-
"""diccionario_A11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12SuktGg9gsx-o5BJ2GV4HyK3xSr-8pVg
"""

import random

# Función que genera un numero aleatorio
def num_aleatorio(nm1,nm2):
    num_random = random.randint(nm1,nm2)
    return num_random

# funcion para elegir 1 o 2 nombres
def nombre_s(nom):
    num_nom = num_aleatorio(1,2)
    if num_nom == 1:
        nombre = random.choice(nom)
    else:
        nombre = random.sample(nom, 2)
    return nombre

def apellidos():
    apellido = ["Ramirez","Contreras","Galindo","Vega","Martinez","Garcia","Castro",
                     "Arredondo","Palafox","Diaz","Lopez","Gomez","Velarde","Hernandez",
                     "Gonzalez","Perez","Rodriguez","Sanchez","Parra","Orci","Ruiz","Flores",
                     "Cruz","Durazo","Grijalva","Nevarez","Palma", "Romero","Medina",
                     "Espinoza","Figueroa"]
    ap = random.choice(apellido)
    am = random.choice(apellido)
    if am == ap:
        ap = random.choice(apellido)
    return ap, am

def nombres(genero):
    if genero == 1:
        sexo = "Femenino"
        nom_femenino = ["Alejandra","Maria","Carolina","Estefany","Ana","Rebeca",
                   "Alicia", "Luz", "Teresa","Andrea", "Sofia","Laura", "Melissa",
                   "Aglaya", "Ivonne","Claudia","Gabriela","Yaritza"]
        nombre = nombre_s(nom_femenino)
    else:
        sexo = "Masculino"
        nom = ["Jose","Ignacio","Adolfo","Lenin","Francisco","Diego", "Fernando",
                    "Pedro","Julio","Fabian", "Luis","Alberto","Antonio","Santiago",
                    "Sebastian","Felipe", "Emiliano","Russell", "Octavio"]
        nombre = nombre_s(nom)

    return sexo, nombre

def registro():
    valores = []
    puesto = ["Gerente", "Supervisor","Operador","Mantenimiento","Tecnico"]
    genero = num_aleatorio(1,2)
         
    valores.append(random.randint(10, 300))
    sexo,nombre = nombres(genero)
    a_paterno,a_materno = apellidos()
    valores.append(nombre)
    valores.append(a_paterno)
    valores.append(a_materno)
    valores.append(sexo)
    valores.append(random.choice(puesto))
    return valores